$countries = [{
    'afghanistan': 'Afghanistan',
    'egypt': 'Ai Cập',
    'albania': 'Albania',
    'algeria': 'Algérie',
    'andorra': 'Andorra',
    'angola': 'Angola',
    'united-kingdom': 'Vương quốc Liên hiệp Anh và Bắc Ireland',
    'antigua-and-barbuda': 'Antigua và Barbuda',
    'austria': 'Áo',
    'saudi-arabia': 'Ả Rập Xê Út',
    'argentina': 'Argentina',
    'armenia': 'Armenia',
    'azerbaijan': 'Azerbaijan',
    'india': 'Ấn Độ',
    'the-bahamas': 'Bahamas',
    'bahrain': 'Bahrain',
    'poland': 'Ba Lan',
    'bangladesh': 'Bangladesh',
    'barbados': 'Barbados',
    'belarus': 'Belarus',
    'belize': 'Belize',
    'benin': 'Bénin',
    'bhutan': 'Bhutan',
    'belgium': 'Bỉ',
    'bolivia': 'Bolivia',
    'bosnia-and-herzegovina': 'Bosna và Hercegovina',
    'botswana': 'Botswana',
    'portugal': 'Bồ Đào Nha',
    'c-te-d-ivoire': 'Bờ Biển Ngà',
    'brazil': 'Brasil',
    'brunei': 'Brunei',
    'bulgaria': 'Bulgaria',
    'burkina-faso': 'Burkina Faso',
    'burundi': 'Burundi',
    'cape-verde': 'Cabo Verde',
    'united-arab-emirates': 'Các Tiểu vương quốc Ả Rập Thống nhất',
    'cameroon': 'Cameroon',
    'cambodia': 'Campuchia',
    'canada': 'Canada',
    'chile': 'Chile',
    'colombia': 'Colombia',
    'comoros': 'Comoros',
    'republic-of-the-congo': 'Cộng hòa Congo',
    'democratic-republic-of-the-congo': 'Cộng hòa Dân chủ Congo',
    'costa-rica': 'Costa Rica',
    'croatia': 'Croatia',
    'cuba': 'Cuba',
    'djibouti': 'Djibouti',
    'dominica': 'Dominica',
    'dominican-republic': 'Cộng hòa Dominica',
    'denmark': 'Đan Mạch',
    'east-timor': 'Timor-Leste',
    'germany': 'Đức',
    'ecuador': 'Ecuador',
    'el-salvador': 'El Salvador',
    'eritrea': 'Eritrea',
    'estonia': 'Estonia',
    'ethiopia': 'Ethiopia',
    'fiji': 'Fiji',
    'gabon': 'Gabon',
    'the-gambia': 'Gambia',
    'ghana': 'Ghana',
    'grenada': 'Grenada',
    'georgia': 'Gruzia',
    'guatemala': 'Guatemala',
    'guinea-bissau': 'Guiné-Bissau',
    'equatorial-guinea': 'Guinea Xích Đạo',
    'guinea': 'Guinée',
    'guyana': 'Guyana',
    'haiti': 'Haiti',
    'the-netherlands': 'Hà Lan',
    'south-korea': 'Hàn Quốc',
    'united-states': 'Hoa Kỳ',
    'honduras': 'Honduras',
    'hungary': 'Hungary',
    'greece': 'Hy Lạp',
    'iceland': 'Iceland',
    'indonesia': 'Indonesia',
    'iran': 'Iran',
    'iraq': 'Iraq',
    'ireland': 'Cộng hòa Ireland',
    'israel': 'Israel',
    'jamaica': 'Jamaica',
    'jordan': 'Jordan',
    'kazakhstan': 'Kazakhstan',
    'kenya': 'Kenya',
    'kiribati': 'Kiribati',
    'kosovo': 'Kosovo',
    'kuwait': 'Kuwait',
    'cyprus': 'Cộng hòa Síp',
    'kyrgyzstan': 'Kyrgyzstan',
    'laos': 'Lào',
    'latvia': 'Latvia',
    'lesotho': 'Lesotho',
    'lebanon': 'Liban',
    'liberia': 'Liberia',
    'libya': 'Libya',
    'liechtenstein': 'Liechtenstein',
    'lithuania': 'Litva',
    'luxembourg': 'Luxembourg',
    'macedonia--fyrom-': 'Cộng hòa Macedonia',
    'madagascar': 'Madagascar',
    'malawi': 'Malawi',
    'malaysia': 'Malaysia',
    'maldives': 'Maldives',
    'mali': 'Mali',
    'malta': 'Malta',
    'morocco': 'Maroc',
    'marshall-islands': 'Quần đảo Marshall',
    'mauritania': 'Mauritanie',
    'mauritius': 'Mauritius',
    'mexico': 'México',
    'micronesia': 'Liên bang Micronesia',
    'moldova': 'Moldova',
    'monaco': 'Monaco',
    'mongolia': 'Mông Cổ',
    'montenegro': 'Montenegro',
    'mozambique': 'Mozambique',
    'myanmar': 'Myanmar',
    'namibia': 'Namibia',
    'south-sudan': 'Nam Sudan',
    'south-africa': 'Cộng hòa Nam Phi',
    'nauru': 'Nauru',
    'norway': 'Na Uy',
    'nepal': 'Nepal',
    'new-zealand': 'New Zealand',
    'nicaragua': 'Nicaragua',
    'niger': 'Niger',
    'nigeria': 'Nigeria',
    'russia': 'Nga',
    'japan': 'Nhật Bản',
    'oman': 'Oman',
    'pakistan': 'Pakistan',
    'palau': 'Palau',
    'palestine': 'Nhà nước Palestine',
    'panama': 'Panama',
    'papua-new-guinea': 'Papua New Guinea',
    'paraguay': 'Paraguay',
    'peru': 'Peru',
    'france': 'Pháp',
    'finland': 'Phần Lan',
    'philippines': 'Philippines',
    'qatar': 'Qatar',
    'romania': 'România',
    'rwanda': 'Rwanda',
    'saint-kitts-and-nevis': 'Saint Kitts và Nevis',
    'saint-lucia': 'Saint Lucia',
    'saint-vincent-and-the-grenadines': 'Saint Vincent và Grenadines',
    'samoa': 'Samoa',
    'san-marino': 'San Marino',
    's-o-tom--and-pr-ncipe': 'São Tomé và Príncipe',
    'czech-republic': 'Cộng hòa Séc',
    'senegal': 'Sénégal',
    'serbia': 'Serbia',
    'seychelles': 'Seychelles',
    'sierra-leone': 'Sierra Leone',
    'singapore': 'Singapore',
    'slovakia': 'Slovakia',
    'slovenia': 'Slovenia',
    'solomon-islands': 'Quần đảo Solomon',
    'somalia': 'Somalia',
    'sri-lanka': 'Sri Lanka',
    'sudan': 'Sudan',
    'suriname': 'Suriname',
    'swaziland': 'Swaziland',
    'syria': 'Syria',
    'tajikistan': 'Tajikistan',
    'tanzania': 'Tanzania',
    'spain': 'Tây Ban Nha',
    'chad': 'Tchad',
    'thailand': 'Thái Lan',
    'turkey': 'Thổ Nhĩ Kỳ',
    'sweden': 'Thụy Điển',
    'switzerland': 'Thụy Sĩ',
    'togo': 'Togo',
    'tonga': 'Tonga',
    'north-korea': 'Cộng hòa Dân chủ Nhân dân Triều Tiên',
    'trinidad-and-tobago': 'Trinidad và Tobago',
    'china': 'Trung Quốc',
    'central-african-republic': 'Cộng hòa Trung Phi',
    'tunisia': 'Tunisia',
    'turkmenistan': 'Turkmenistan',
    'tuvalu': 'Tuvalu',
    'australia': 'Úc',
    'uganda': 'Uganda',
    'ukraine': 'Ukraina',
    'uruguay': 'Uruguay',
    'uzbekistan': 'Uzbekistan',
    'vanuatu': 'Vanuatu',
    'vatican-city': 'Thành Vatican',
    'venezuela': 'Venezuela',
    'vietnam': 'Việt Nam',
    'italy': 'Ý',
    'yemen': 'Yemen',
    'zambia': 'Zambia',
    'zimbabwe': 'Zimbabwe'
}];